# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mail.from: 'Gmail for send mail'
    mail.login: 'Your Gmail login'
    mail.password: 'Your Gmail password'
    mail.message.flight_cancel.header: 'Flight canceled' #header message
    mail.message.flight_cancel.text: 'We apologize, flight canceled. Flight code: ' #message value (after message added number flight code)
    provider_key: 'IJ12Jfgvck3DSGG234dsdfNHBXndsjs71j8fJ8kLLvhakvk323'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
